### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by decembboy**

### CODE REVIEW

**Review by decembboy — COMMENTED** [review]
Description of the complete project plan

**Comment by fatchat** [comment]
Thank you, please tell me who you are and why you submitted this PR out of the blue?

**Comment by decembboy** [comment]
Hello, my name is Deborshi. I'm interested in participating in the Code for Govtech program and would like to boost my chances of being selected by earning points

**Comment by decembboy** [comment]
> Thank you, please tell me who you are and why you submitted this PR out of the blue?

Hello, my name is Deborshi. I'm interested in participating in the Code for Govtech program and would like to boost my chances of being selected by earning points

**Pull request closed without merging**
