### PR TITLE
feature: added a side menu

### LINKED ISSUE #8: Add a Side Menu
## Description
Add a side menu to the application

## Goals
- [ ] [A hideable side menu]
- [ ] [Hidden by default on mobile view]

## Expected Outcome
A vertical menu on the left hand side of the layout. Visible by default on desktops, hidden by default on mobile. Toggle visibility by clicking a hamburger icon at the top

## Acceptance Criteria
- [ ] [Visible by default on desktop]
- [ ] [Hidden by default on mobile]
- [ ] [Toggle visibility]
- [ ] [Easy for developers to add menu items]
- [ ] [Menu items are attached to routes]
- [ ] [Possible to add separators]
- [ ] [Two sets of menu items - top set and bottom set. Bottom set can be empty]

## Implementation Details
Bootstrap 5

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
HTML

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
UI/UX/Design, Feature

### Sub Category
Frontend, Mobile, Beginner friendly

### PR DESCRIPTION
**Pull request by Min2who**
https://github.com/DalgoT4D/dalgo-admin/assets/127925465/8f3f7557-ed98-45fd-81de-ace6fe562a0b

resolves #8

### CODE REVIEW

**Comment by amansgith** [comment]
Hii @Min2who the side bar looks fine but i think you should style it a bit more.. so that the links are move visible and the toggle button also should look good.. Also as it may be available in different pages  so i think you may add it in a component in the template folder..
Rest lies on Sir as he may want it to look

**Comment by fatchat** [comment]
nice job @Min2who 

i agree with @amansgith ... did you try looking for templates online? don't spend too much time with CSS and styling, other people have already done this and made their work available for us to use

**Comment by jayesh9747** [comment]
@Min2who please look up  bootstrap documentation for side menu it is very simple to use .

**Comment by fatchat** [comment]
@Min2who one PR was merged into `main`, make sure to pull those changes into your branch before proceeding!

GitHub has a button to do this... but if there are conflicts you will need to resolve them on your machine. For this reason I usually don't use the GitHub button to update branches

**Comment by fatchat** [comment]
closing due to lack of activity

**Pull request closed without merging**
