### PR TITLE
Added Side_menu

### LINKED ISSUE #8: Add a Side Menu
## Description
Add a side menu to the application

## Goals
- [ ] [A hideable side menu]
- [ ] [Hidden by default on mobile view]

## Expected Outcome
A vertical menu on the left hand side of the layout. Visible by default on desktops, hidden by default on mobile. Toggle visibility by clicking a hamburger icon at the top

## Acceptance Criteria
- [ ] [Visible by default on desktop]
- [ ] [Hidden by default on mobile]
- [ ] [Toggle visibility]
- [ ] [Easy for developers to add menu items]
- [ ] [Menu items are attached to routes]
- [ ] [Possible to add separators]
- [ ] [Two sets of menu items - top set and bottom set. Bottom set can be empty]

## Implementation Details
Bootstrap 5

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
HTML

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
UI/UX/Design, Feature

### Sub Category
Frontend, Mobile, Beginner friendly

### PR DESCRIPTION
**Pull request by harshit6174**
Added  a side menu with the required features and improved styling.
closes #8

### CODE REVIEW

**Comment by fatchat** [comment]
hi @harshit6174 
please see the discussion at https://github.com/DalgoT4D/dalgo-admin/pull/19 and make appropriate updates

**Comment by harshit6174** [comment]
sure @fatchat i am going to update the branch to the main branch and also the changes required as you mentioned in #20

**Comment by fatchat** [comment]
@harshit6174 shall we close this, doesn't look like you're able to work on it

**Comment by harshit6174** [comment]
yes you may close this @fatchat ,learnt a few new things working on this issue ,thanks for the opportunity

**Pull request closed without merging**
