### PR TITLE
#isssue2 Add authentication 

### PR DESCRIPTION
**Pull request by jayesh9747**
Hello @fatchat, could you please review my pull request and any related issues or modifications? If you identify any specific issues, kindly provide details so that I can promptly address and improve the code accordingly. Your feedback is greatly appreciated, and I am committed to making the necessary corrections to ensure a robust and well-structured code. Thank you!

### CODE REVIEW

**Comment by jayesh9747** [comment]
can i share my google api key for testing on linkdin ?

**Comment by amansgith** [comment]
@jayesh9747 If possible you should add a short video of the feature working locally or add relevant screenshots
This way it will be easier for Review by Sir :)

**Comment by jayesh9747** [comment]
@amansgith  Sure .

**Comment by jayesh9747** [comment]
I have implemented authentication functionality using the AllAuth library, utilized AllAuthUI for the user interface, and for testing purposes, I have integrated my Google authentication API key provided through the environment file

https://github.com/DalgoT4D/dalgo-admin/assets/123955234/967f5a83-93b1-4440-9a10-f86a6f0d8cc5

**Comment by jayesh9747** [comment]
some screenshots: 
image
image
image
image

**Comment by amansgith** [comment]
@jayesh9747 
Have you done the restriction of the domain feature as mentioned by sir that only domains "@projecttech4dev.org" for google auth..
also check if the data of sign up going to database(postgres)

**Comment by fatchat** [comment]
thank you @jayesh9747 

i got got done with a week-long T4D sprint / conference / workshop ... taking the next three days off

looking forward to looking at this next week

don't share api keys over linkedin or anywhere else, i'll test using my own

thanks @amansgith for the collaboration

**Comment by jayesh9747** [comment]
@amansgith  Sure, sir. I have a request to restrict the usage of the API key to domains with the suffix '@projecttech4dev.org.' This restriction can be implemented using Google Developer Tools, ensuring that the API key is configured accordingly during its creation

**Comment by fatchat** [comment]
good morning @jayesh9747 

looking good! i successfully logged in using username+password as well as using google oauth

in both cases the template at `dashboard/home.html` was correctly populated 

last request before i merge ... could you remove the "sign up" functionality? we only want "sign in" with an existing account. 

thank you

**Comment by fatchat** [comment]
@jayesh9747 we will do forgot-password later, not urgent right now and also it will require setting up an email service

**Comment by jayesh9747** [comment]
@fatchat,   So right now I only remove signup functionality . Thank you sir

**Comment by jayesh9747** [comment]
I have implemented the ability to close the signup functionality, ensuring that it can be easily reopened in the future whenever necessary like this , 
image

**Comment by jayesh9747** [comment]
@fatchat, could you please review the signup closing functionality and consider merging my pull request?

**Review by fatchat — APPROVED** [review]

**Comment by jayesh9747** [comment]
@fatchat  so now, can i start to work on issue #4 ?

**Comment by fatchat** [comment]
@jayesh9747 yes absolutely. i wrote a short wiki page to answer your most recent question on that thread

**Comment by jayesh9747** [comment]
closes #2

**Pull request merged**
