### PR TITLE
Added sidemenu

### PR DESCRIPTION
**Pull request by vilol-04**
Please review and let me know the changes. @fatchat

### CODE REVIEW

**Comment by fatchat** [comment]
@vilol-04 could you add `venv` to the `.gitignore` and remove the folder from source control please?

**Comment by vilol-04** [comment]
@fatchat Is it alright?

**Comment by fatchat** [comment]
this is definitely coming together. i'm going to make some notes for our mutual tracking

1. no sidemenu when logged out
2. sidemenu appears when logged in
3. sidemenu appears on "client details" page
4. sidemenu does not appear on "infrastructure" page
5. sidemenu menu items are currently placeholders
6. no navigation bar on any pages

i'm guessing point (4) is related to your css question? i don't know... i would have to spend time on it to figure it out. i tried doing what you did for (3) and django complained:

```
Invalid block tag on line 17: 'static', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
```

when it got to the 
```
<img class="logo airbyte-logo" src="{% static '..\static\airbyte-logo.png' %}" alt="Logo">
```

Now I'll observer that this worked before i put it inside a `{% block content %}` so it has something to do with that. you may be able to google a solution from this point

**Comment by vilol-04** [comment]
I am not getting any such error in my system @fatchat

**Comment by vilol-04** [comment]
@fatchat I have made some changes. Please look into it.

**Comment by fatchat** [comment]
@vilol-04 i have merged aman's PR https://github.com/DalgoT4D/dalgo-admin/pull/23 

please merge those changes into your branch 

thank you

**Comment by vilol-04** [comment]
@fatchat Please review and let me know what to change.

**Comment by fatchat** [comment]
@vilol-04 

1. sidemenu contains correct navigation links now
2. sidemenu appears on infrastructure page now
3. navigation bar on all pages now

this is great. now i have one small request:
- on the home page just say "welcome" and nothing else, remove all the "your username", "get client details" etc etc

there is also one bug to fix, something with your bootstrap navbar... see this screenshot

image

somehow the logo and the menu button are overlapping. hopefully will be easy to fix

everything else is looking good

**Comment by vilol-04** [comment]
@fatchat please review

**Review by fatchat — APPROVED** [review]

**Pull request merged**
