### PR TITLE
Added toggled side menu

### PR DESCRIPTION
**Pull request by vilol-04**
Please review and let me know what to change. @fatchat

### CODE REVIEW

**Comment by fatchat** [comment]
would you update the branch please @vilol-04 ? i.e. `git merge main` and then push again

**Comment by vilol-04** [comment]
Screenshot (127)
It's already updated.

**Comment by fatchat** [comment]
Did you switch to main and do a git pull?

**Comment by vilol-04** [comment]
Screenshot (128)
It's done.

**Comment by fatchat** [comment]
thank you

how does this work with the rest of the application? i see `<html>`, `<head>` and `<body>` tags... as if it's a standalone page

**Comment by vilol-04** [comment]
There is a error on my part. I'll rectify asap. Sorry for the inconvenience.

**Comment by fatchat** [comment]
@vilol-04 
i see an html file which presumably shows a nice looking side menu. but this has not been integrated into the rest of the application

1. the side menu needs to show whenever a user is logged in
2. other pages should appear in the main frame to the right of the side menu
3. other pages should have no knowledge of the side menu i.e. their code should not refer to the side menu

**Comment by fatchat** [comment]
closing due to lack of activity

**Pull request closed without merging**
