### PR TITLE
issue #4 Create a Client Overview page

### PR DESCRIPTION
**Pull request by jayesh9747**
The web page that displays details for a specific client, including information about data sources and pipeline configurations. Additionally, it includes dynamic routing functionality, allowing users to navigate to the details page of individual clients.

### CODE REVIEW

**Comment by fatchat** [comment]
hi @jayesh9747 

migrations need to be checked into source control ... i see that you are blocking them in `.gitignore`

you can ignore the `.pyc` files

**Comment by jayesh9747** [comment]
@fatchat  i updated gitignorefile, plaese review. i share mock data on discord

**Review by fatchat — APPROVED** [review]

**Comment by jayesh9747** [comment]
@fatchat  what is the next task or issue?

**Comment by jayesh9747** [comment]
closes #4

**Pull request merged**
